"""add description and price columns

Revision ID: 3ec5fff3440f
Revises: 7626f82f9a7a
Create Date: 2025-04-25 15:58:55.956864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec5fff3440f'
down_revision = '7626f82f9a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('adoption_applications', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
